### ISSUE TITLE
Issues with kdbus.match documentation

### ISSUE THREAD

**Issue by heftig** [systemd/kdbus#3]
https://github.com/systemd/kdbus/blob/devel/Documentation/kdbus/kdbus.match.xml#L218 says:

```xml
            <varlistentry>
              <term><constant>KDBUS_MATCH_REPLACE</constant></term>
              <listitem>
                <para>Make the endpoint file group-accessible</para>
              </listitem>
            </varlistentry>
```
Is obviously wrong. My guess is the paragraph should be:
```xml
                <para>Remove all previously existing matches with the same cookie</para>
```

https://github.com/systemd/kdbus/blob/devel/Documentation/kdbus/kdbus.match.xml#L407 says:
```xml
      <varlistentry>
        <term><varname>flags</varname></term>
        <listitem><para>
          No flags are supported for this use case.
          <constant>KDBUS_FLAG_NEGOTIATE</constant> is accepted to probe for
          valid flags. If set, the ioctl will fail with
          <errorcode>-1</errorcode>, <varname>errno</varname> is set to
          <constant>EPROTO</constant>, and the <varname>flags</varname> field
          is set to <constant>0</constant>.
        </para></listitem>
      </varlistentry>
```
This is a bit confusing, reading as if `If set, the ioctl will fail` applies to `KDBUS_FLAG_NEGOTIATE`.

**Comment by zonque** [comment]
On 06/29/2015 09:58 AM, Jan Alexander Steffens wrote:
> https://github.com/systemd/kdbus/blob/devel/Documentation/kdbus/kdbus.match.xml#L218
> says:
> 
>             <varlistentry>
>               <term><constant>KDBUS_MATCH_REPLACE</constant></term>
>               <listitem>
>                 <para>Make the endpoint file group-accessible</para>
>               </listitem>
>             </varlistentry>
> 
> Is obviously wrong. My guess is the paragraph should be:
> 
>                 <para>Remove all previously existing matches with the same cookie</para>

Correct, thanks fpr spotting this. I fixed this now in commit b74e4ba in
the devel branch.

> https://github.com/systemd/kdbus/blob/devel/Documentation/kdbus/kdbus.match.xml#L407
> says:
> 
>       <varlistentry>
>         <term><varname>flags</varname></term>
>         <listitem><para>
>           No flags are supported for this use case.
>           <constant>KDBUS_FLAG_NEGOTIATE</constant> is accepted to probe for
>           valid flags. If set, the ioctl will fail with
>           <errorcode>-1</errorcode>, <varname>errno</varname> is set to
>           <constant>EPROTO</constant>, and the <varname>flags</varname> field
>           is set to <constant>0</constant>.
>         </para></listitem>
>       </varlistentry>
> 
> This is a bit confusing, reading as if |If set, the ioctl will fail|
> applies to |KDBUS_FLAG_NEGOTIATE|.

Yes, that's what it does. The |KDBUS_FLAG_NEGOTIATE| flag behaves the
same for all ioctls. Right now, it does make much sense for this one,
but if ever add flag to this command, it will be returned during
negotiation. Passing an /invalid/ flag will result in `EINVAL`. Makes sense?

**Comment by heftig** [comment]
So, genetically, if an empty set of features/flags/items is returned for a negotiation query, it causes an EPROTO error?

**Comment by zonque** [comment]
I think you can simply use `read_full_file()` here instead, which also removes the ugly fixed-sized buffer on the stack.

**Comment by zonque** [comment]
(sorry, the previos comment was totally unreleated, so I removed it again)

**Comment by zonque** [comment]
Ok, you spotted a documentation bug here. The return value in cases of negotiation is `0,` not `-EPROTO`. Will commit a patch later that fixes that.

Thanks!

**Comment by zonque** [comment]
Documentation was now changed in 8db99ac11e. Thanks again!
